// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Branding: typeof import('./components/Branding.vue')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CovidChart: typeof import('./components/CovidChart.vue')['default']
    DashboardSidebar: typeof import('./components/DashboardSidebar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    ReactiveCovidChart: typeof import('./components/ReactiveCovidChart.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleChart: typeof import('./components/SampleChart.vue')['default']
    SidebarUserMenu: typeof import('./components/SidebarUserMenu.vue')['default']
  }
}
